### PR TITLE
Isolate test code

### PR DESCRIPTION
**Pull request by mrtorrent**
Hi folks, these are a few fixes for some test code that was being run in the production environment (rcov task and rspec-on-rails-matchers). If you bundle installed without the "test" and "testing" groups, this would cause rake commands to fail.

### CODE REVIEW

**Comment by jrom** [comment]
Hey @mrtorrent, that's awesome. Let me check it and pull it if it makes sense!

**Comment by saimonmoore** [comment]
yeah thanks for this @mrtorrent. We kept meaning to look into this but hadn't found the time

**Comment by mrtorrent** [comment]
My pleasure, glad I could help.
On Sep 20, 2011 10:59 PM, "Saimon Moore" <
reply@reply.github.com>
wrote:

**Comment by unixcharles** [comment]
thanks, got that fixed in the dev branch but master hasn't been merge in a long time now. It was especially annoying since it break Heroku rake task for example.

**Comment by mrtorrent** [comment]
Should I be developing against the dev branch? Is it tracking the
current teambox.com release?

**Comment by unixcharles** [comment]
Yes, dev is the branch you can see on teambox.com. This is where we do daily development, its a bit confusing

**Pull request merged**
