### PR TITLE
More task update fixes

### PR DESCRIPTION
**Pull request by nvier**

### CODE REVIEW

**Comment by unixcharles** [comment]
thanks @denisnovikov for the fix

I don't know the details of the bug, this need a failing test so it won't happen again. Can you explain me the bug so I can write spec or it or provide us a failing test?

**Comment by nvier** [comment]
It's extending https://github.com/teambox/teambox/commit/014eaa32697615daaadb2921f4b16bdc7059cd34 fix :)

**Comment by nvier** [comment]
And details on this were here: https://teambox.com/projects/teambox/tasks/332866

**Comment by jrom** [comment]
Thank you @denisnovikov! I'll add a test for this case, but I know this was needed, just experienced this bug right now (again).

**Comment by nvier** [comment]
You're welcome. There is another one issue like this described and fixed here: https://github.com/denisnovikov/teambox/commit/820dd90faa6295e8673196adb2d25b2a8b4b41f9

**Pull request merged**
