### PR TITLE
Unwatch Conversations and Tasks within a single click

### PR DESCRIPTION
**Pull request by nvier**
This fixes https://teambox.com/projects/teambox/tasks/104422

No test made, since they are look funny I didn't get them yet.

### CODE REVIEW

**Comment by jamesu** [comment]
Looks great

**Comment by nvier** [comment]
What's it? o_O

**Comment by jrom** [comment]
Hi there, can you give me a link to the commit you want us to pull? Thanks!

**Comment by nvier** [comment]
It was quite blown within a few commits, I will find a patch later today (hopefully I have it somewhere)

**Pull request closed without merging**
